const Action = {
    clear: 'Clear',
    click: 'Click',
    close: 'Close',
    contextClick: 'ContextClick',
    doubleClick: 'DoubleClick',
    dragAndDrop: 'DragAndDrop',
    execute: 'Execute',
    getAttribute: 'GetAttribute',
    getText: 'GetText',
    getTitle: 'GetTitle',
    insert: 'Insert',
    keyDown: 'KeyDown',
    keyUp: 'KeyUp',
    keyboard: 'Keyboard',
    mouse: 'Mouse',
    move: 'Move',
    navigate: 'Navigate',
    quit: 'Quit',
    sendKeys: 'SendKeys',
    takeScreenshot: 'TakeScreenshot'
}